name: run all checks


# on: [push, pull_request]
# on: pull_request
on: 
  push:
  pull_request:
    branches: 
      - master
jobs:
  # 各種toolsごとにbuild & runすればいい
  build_check_upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: mark
        run: echo "START BUILDING"
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run all checks 
        run: ./sample/gradlew -b sample/build.gradle checkstyleMain pmdMain spotbugsMain dependencyCheckAnalyze
      - name: debug
        run: ./sample
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: all-reports
          path: ./sample/out
  printout:
    runs-on: ubuntu-latest
    needs: [build_check_upload]
    steps:
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: all-reports
      - name: echo
        shell: bash
        run: |
          ls all-reports
